name: Deploy Jupyter Book

on:
  push:
    branches:
      - main  # Runs on every push to main

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.9"

    - name: Install dependencies
      run: |
        pip install jupyter-book ghp-import

    - name: Build the Jupyter Book
      run: |
        jupyter-book build .

    - name: Deploy to GitHub Pages
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git config --global user.name "github-actions[bot]"
        git clone --depth 1 --branch gh-pages https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git gh-pages
        rsync -av --delete _build/html/ gh-pages/
        cd gh-pages
        git add .
        git commit -m "Deploy Jupyter Book via GitHub Actions" || echo "No changes to commit"
        git push origin gh-pages
  